<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="/admin/global_assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/layout.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/components.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/colors.min.css" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->